### ISSUE TITLE
Please don't add people randomly to your repo without asking

### ISSUE THREAD

**Issue by sindresorhus** [kamranahmedse/githunt#1]
It wastes my time and is a good way to get yourself blocked.

https://twitter.com/sindresorhus/status/694999624852045824

**Comment by kamranahmedse** [comment]
Oops, thought I could get your feedback. Anyways, considered. Thanks

**Comment by sindresorhus** [comment]
This is not the way to do it. Reach out on Twitter instead. I'm always happy to give feedback ;)

**Comment by kamranahmedse** [comment]
Noted. Thanks :)
