### ISSUE TITLE
[Bug] wrong repo watch number

### ISSUE THREAD

**Issue by linhuiw** [kamranahmedse/githunt#31]
The repo watch number is wrong displayed.
the watch number is the same as the star number.

Pic:
![image](https://user-images.githubusercontent.com/722603/53220626-8bd26700-36a0-11e9-9076-ee87979d36a9.png)

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. This is the bug in GitHub's API which is returning the watcher count same as the star count - we can't do anything about it unfortunately.
