### ISSUE TITLE
Broken for against Content Security Policy

### ISSUE THREAD

**Issue by ntnyq** [kamranahmedse/githunt#34]
Didn't work since this morning and got an error message bellow

`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem: chrome-extension-resource:". Either the 'unsafe-inline' keyword, a hash ('sha256-5As4+3YpY62+l38PsxCEkjB1R4YtyktBtRScTJ3fyLU='), or a nonce ('nonce-...') is required to enable inline execution.` 

This is on

- Mac OS v10.14.5
- Google Chrome v74.0.3729.169 (Official Build) (64-bit)

**Comment by TotomInc** [comment]
Also getting this error since this morning:

- Windows 10
- Google Chrome v75.0.3770.100

**Comment by kamranahmedse** [comment]
Thank you for reporting. 
This has been fixed in the recent update. Let me know if you still face issues.
